[package]
name = "git-ez"
version = "0.0.2"
authors = ["Lilis Iskandar <lilis@veand.co>"]

[profile.release]
opt-level = 'z'
lto = true
panic = "abort"

[dependencies]
clap = "2"
dirs = "1"
serde_derive = "1"
serde = "1"
toml = "0.4"
